import { TopoComponent } from './../topo.component';
import { Injectable } from '@angular/core';
import {Pais} from './pais';
@Injectable()

export class DataserviceService {
    obterPaises(){
        return [
            new Pais (1,'AF','Afeganistão','AFG'),
            new Pais (2,'ZA','África do Sul	','ZAF'),
            new Pais (3,'AL','Albânia','ALB'),
            new Pais (4,'DE','Alemanha','DEU'),
            new Pais (5,'AD','Andora','AND'),
            new Pais (6,'AO','Angola','AGO'),
            new Pais (7,'AI','Anguilla','AIA'),
            new Pais (8,'ZA','África do Sul	','ZAF'),
            new Pais (9,'ZA','África do Sul	','ZAF'),
            new Pais (10,'AQ','Antarctica','ATA'),
            new Pais (11,'AG','Antígua e Barbuda','ATG'),
            new Pais (12,'AR','Argentina','ARG'),
            new Pais (13,'DZ','Argélia','DZA'),
            new Pais (14,'AM','Arménia','ARM'),
            new Pais (15,'AW','Aruba','ABW'),
            new Pais (16,'SA','Arábia Saudita','SAU'),
            new Pais (17,'AU','Austrália','AUS'),
            new Pais (18,'AT','Áustria','AUT'),
            new Pais (19,'AZ','Azerbaijão','AZE'),
            new Pais (20,'BS','Bahamas','BHS'),
            new Pais (21,'BH','Bahrein','BHR'),
            new Pais (22,'BG','Bahrein','BGD'),
            new Pais (23,'BB','Barbados','BRD'),
            new Pais (24,'BE','Bélgica','BEL'),
            new Pais (25,'BZ','Belize','BLZ'),
            new Pais (26,'BJ','Benim','BEN'),
            new Pais (27,'BM','Bermuda','BMU'),
            new Pais (28,'BT','Butão','BTN'),
            new Pais (29,'BY','Bielorrússia','BLR'),
            new Pais (30,'BO','Bolívia','BOL'),
            new Pais (31,'BA','Bósnia e Herzegovina	','BIH'),
            new Pais (32,'BW','Botswana','BWA'),
            new Pais (33,'BR','Brasil','BRA'),
            new Pais (34,'IO','British Indian Ocean Territory','IOT'),
            new Pais (35,'BN','Brunei','BRN'),
            new Pais (36,'BG','Bulgária','BGR'),
            new Pais (37,'BF','Burkina Faso','BFA'),
            new Pais (38,'MM','Myanmar (Burma)','MMR'),
            new Pais (39,'BI','Burundi','BDI'),
            new Pais (40,'CM','Camarões','CMR'),
            new Pais (41,'CV','Cabo Verde','CVP'),
            new Pais (42,'KH','Camboja','KHM'),
            new Pais (43,'CA','Canadá','CAN'),
            new Pais (44,'QA','Catar','QAT'),
            new Pais (45,'TD','Chad','TCD'),
            new Pais (46,'CL','Chile','CHL'),
            new Pais (47,'CH','China','CHN'),
            new Pais (48,'CY','Chipre','CYP'),
            new Pais (49,'CX','Christmas Island','CXR'),
            new Pais (50,'SG','Cingapura','SGP'),
            new Pais (51,'CO','Colômbia','COL'),
            new Pais (52,'KM','Comores','COM'),
            new Pais (53,'KP','Coreia do Norte','PRK'),
            new Pais (54,'CR','Coreia do Sul','KOR'),
            new Pais (55,'CI','Costa do Marfim','CIV'),
            new Pais (56,'CR','Costa Rica','CRV'),
            new Pais (57,'HR','Croácia','HRV'),
            new Pais (58,'CU','Cuba','CUB'),
            new Pais (59,'DK','Dinamarca','DNK'),
            new Pais (60,'DJ','Djibouti','DJI'),
            new Pais (61,'DM','Dominica','DMA'),
            new Pais (62,'EG','Egito','EGY'),
            new Pais (63,'SV','El Salvador','SLV'),
            new Pais (64,'AE','Emirados Árabes Unidos','ARE'),
            new Pais (65,'EC','Equador','ECU'),
            new Pais (66,'ER','Eritreia','ERI'),
            new Pais (67,'EE','Estónia','EST'),
            new Pais (68,'ES','Espanha','ESP'),
            new Pais (69,'ET','Etiópia','ETH'),
            new Pais (70,'FJ','Fiji','FJI'),
            new Pais (71,'FI','Finlândia','FIN'),
            new Pais (72,'FR','França','FRA'),
            new Pais (73,'GA','Gabão','GAB'),
            new Pais (74,'GM','Gâmbia','GMB'),
            new Pais (75,'','Banda de Gaza (Palestina)',''),
            new Pais (76,'GE','Geórgia','GEO'),
            new Pais (77,'GA','Gana','GHA'),
            new Pais (78,'GI','Gibraltar','GIB'),
            new Pais (79,'GR','Grécia','GRC'),
            new Pais (80,'GL','Groelândia','GRL'),
            new Pais (81,'GD','Granada','GRD'),
            new Pais (82,'GL','Guam','GUM'),
            new Pais (82,'GM','Groelândia','GRL'),
            new Pais (83,'GT','Guatemala','GTM'),
            new Pais (84,'GY','Guiana','GUY'),
            new Pais (85,'GL','Guiné','GRL'),
            new Pais (86,'GQ','Guiné Equatorial','GNQ'),
            new Pais (87,'GW','Guiné-Bissau','GNB'),
            new Pais (88,'HT','Haiti','HTI'),
            new Pais (89,'HN','Honduras','HND'),
            new Pais (90,'HK','Hong Kong','HKG'),
            new Pais (91,'HU','Hungria','HUN'),
            new Pais (92,'IS','Islândia','IS'),
            new Pais (93,'KY','Ilhas Cayman','CYM'),
            new Pais (94,'CC','Ilhas Cocos (Keeling)','CCK'),
            new Pais (95,'IM','Ilha de Man','IMN'),
            new Pais (96,'CK','Ilhas Cook','COK'),
            new Pais (97,'FK','Ilhas Falkland (Malvinas)','FLK'),
            new Pais (98,'FO','Ilhas Feroé','FRO'),
            new Pais (99,'MP','Ilhas Mariana do Norte','MNP'),
            new Pais (100,'MH','Ilhas Marshall','MHL'),
   
        ]
    }
constructor(){}
}